
# This is register this service to the service Registry as a client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

